// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_replace`, `container`, `digest`, `display_path`, `fingerprint`, `move_new`, `plain_path`, `prepared`, `redirects_path`, `reserve_near`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Prepared`, `Staged`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Read-only preview. The opaque fingerprint binds content, size, time and file ID.
Future<String> prepareAudioTrim({required String sourcePath}) =>
    RustLib.instance.api
        .crateApiAudioTrimPrepareAudioTrim(sourcePath: sourcePath);

/// Returns the same Audio JSON schema as indexing, also for the app's own temp file.
Future<String> readAudioTrimFile({required String path}) =>
    RustLib.instance.api.crateApiAudioTrimReadAudioTrimFile(path: path);

/// Returns JSON {text, adjusted, warning}; unknown timed formats remain intact.
Future<String> trimAudioLyricText(
        {required String text,
        required double startSeconds,
        required double endSeconds}) =>
    RustLib.instance.api.crateApiAudioTrimTrimAudioLyricText(
        text: text, startSeconds: startSeconds, endSeconds: endSeconds);

/// Idempotent cleanup for canceled/failed jobs, including already removed temps.
Future<void> releaseAudioTrim({required String temporaryPath}) =>
    RustLib.instance.api
        .crateApiAudioTrimReleaseAudioTrim(temporaryPath: temporaryPath);

/// Transfers native tags to an already encoded temporary file. Nothing writes to
/// the source. A changed/missing native field or picture rejects preservation.
Future<String> finishAudioTrimMetadata(
        {required String sourcePath,
        required String temporaryPath,
        required bool preserveMetadata,
        String? title,
        String? artist,
        String? album,
        required double startSeconds,
        required double endSeconds}) =>
    RustLib.instance.api.crateApiAudioTrimFinishAudioTrimMetadata(
        sourcePath: sourcePath,
        temporaryPath: temporaryPath,
        preserveMetadata: preserveMetadata,
        title: title,
        artist: artist,
        album: album,
        startSeconds: startSeconds,
        endSeconds: endSeconds);

/// Copies never replace an existing file. Overwrite accepts only the original
/// source path, validates its strong preview fingerprint, and keeps a backup.
Future<String> commitAudioTrim(
        {required String sourcePath,
        required String temporaryPath,
        required String destinationPath,
        required bool overwrite,
        required String expectedFingerprint}) =>
    RustLib.instance.api.crateApiAudioTrimCommitAudioTrim(
        sourcePath: sourcePath,
        temporaryPath: temporaryPath,
        destinationPath: destinationPath,
        overwrite: overwrite,
        expectedFingerprint: expectedFingerprint);
