// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `animated`, `normalize`, `read_cover_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Validate and prepare an import copy; never write to the selected source.
/// FRB runs this ordinary function on its native worker pool, not the UI thread.
Future<ImportedCoverImage> normalizeCoverImage({required List<int> data}) =>
    RustLib.instance.api.crateApiCoverImageNormalizeCoverImage(data: data);

class ImportedCoverImage {
  final Uint8List bytes;
  final String extension_;
  final int width;
  final int height;

  const ImportedCoverImage({
    required this.bytes,
    required this.extension_,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^ extension_.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportedCoverImage &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          extension_ == other.extension_ &&
          width == other.width &&
          height == other.height;
}
