// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `metadata_fingerprint`

/// Read-only preview, using exactly the container probe used by safe edits.
/// Neither extension guesses nor the cached library are evidence of writability.
Future<String> preflightAudioMetadata({required String path}) =>
    RustLib.instance.api
        .crateApiMetadataPreflightPreflightAudioMetadata(path: path);
