// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_get_lyric_from_lofty`, `_get_lyric_from_lrc_file`, `_get_picture_by_lofty`, `_get_picture_by_windows`, `apply_tag_values`, `artist_from_tags_with_source`, `capture`, `check_metadata_fingerprint`, `copy_of`, `cover_decode_dimensions`, `disarm`, `ensure_tag`, `first_tag_text_with_source`, `is_edited_metadata_key`, `is_metadata_transaction_path`, `is_supported_audio_path`, `metadata_error`, `metadata_io_error`, `metadata_is_missing`, `metadata_message`, `move_file_without_replacing`, `multiset_contains`, `multithreaded`, `needs_classification_backfill`, `needs_duration_backfill`, `new_with_path`, `normalize_decoded_id3_flags`, `ordered_tags`, `panic_payload_to_string`, `path`, `preserve_legacy_language_frames`, `probe_tagged_audio`, `read_by_lofty`, `read_by_win_music_properties`, `read_from_path`, `read_index_json`, `read_tagged_file_by_content`, `replace_with_rollback`, `reserve_transaction_path`, `resize_picture`, `same_existing_file`, `sanitize_file_name`, `save_edited_primary_tag`, `sibling_path`, `text_from_tag`, `text_looks_misdecoded`, `to_json_value`, `unused_transaction_path`, `verify_metadata_edit`, `verify`, `write_index_json`, `write_metadata_with_expectation`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioPropertiesSnapshot`, `Audio`, `ComApartment`, `PreservedMetadata`, `PreservedTag`, `TransactionPath`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `drop`, `drop`, `eq`, `fmt`, `fmt`, `from`

/// Prepare a unique cancellation identity before dispatching a native scan.
String createIndexScanTask() =>
    RustLib.instance.api.crateApiTagReaderCreateIndexScanTask();

/// Returns cancelling, committing, or finished; never interrupts a commit.
String cancelIndexScanTask({required String taskId}) =>
    RustLib.instance.api.crateApiTagReaderCancelIndexScanTask(taskId: taskId);

void releaseIndexScanTask({required String taskId}) =>
    RustLib.instance.api.crateApiTagReaderReleaseIndexScanTask(taskId: taskId);

Future<String> updateAudioMetadata(
        {required String path,
        required String fileName,
        required String title,
        required String artist,
        required String album,
        String? picturePath,
        String? expectedFingerprint}) =>
    RustLib.instance.api.crateApiTagReaderUpdateAudioMetadata(
        path: path,
        fileName: fileName,
        title: title,
        artist: artist,
        album: album,
        picturePath: picturePath,
        expectedFingerprint: expectedFingerprint);

/// for Flutter
/// 如果无法通过 Lofty 获取则通过 Windows 获取
Future<Uint8List?> getPictureFromPath(
        {required String path, required int width, required int height}) =>
    RustLib.instance.api.crateApiTagReaderGetPictureFromPath(
        path: path, width: width, height: height);

/// for Flutter
/// 只支持读取 ID3V2, VorbisComment, Mp4Ilst 存储的内嵌歌词
/// 以及相同目录相同文件名的 .lrc 外挂歌词（utf-8 or utf-16）
Future<String?> getLyricFromPath({required String path}) =>
    RustLib.instance.api.crateApiTagReaderGetLyricFromPath(path: path);

/// for Flutter
/// 扫描给定路径下所有子文件夹（包括自己）的音乐文件并把索引保存在 index_path/index.json。
Stream<IndexActionState> buildIndexFromFoldersRecursively(
        {required List<String> folders,
        required String indexPath,
        String? taskId}) =>
    RustLib.instance.api.crateApiTagReaderBuildIndexFromFoldersRecursively(
        folders: folders, indexPath: indexPath, taskId: taskId);

/// Read-only recursive discovery plus size/nanosecond-time change detection.
/// The complete result is committed atomically; failed enumeration leaves the
/// old index intact. Full rebuilding is available through the separate API.
Stream<IndexActionState> updateIndex(
        {required String indexPath, String? taskId}) =>
    RustLib.instance.api
        .crateApiTagReaderUpdateIndex(indexPath: indexPath, taskId: taskId);

class IndexActionState {
  /// completed / total
  final double progress;

  /// describe action state
  final String message;

  const IndexActionState({
    required this.progress,
    required this.message,
  });

  @override
  int get hashCode => progress.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexActionState &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          message == other.message;
}
